book_shelf_v2/config/routes.rb
Rails.application.routes.draw do
  resources :books
  root "books#index"
  
  get 'books/index'

end

book_shelf_v2/app/models/book.rb
class Book < ActiveRecord::Base
end

book_shelf_v2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

book_shelf_v2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  def index
    @books = Book.all
  end
  
  def set_book
    @book = Book.find(params[:id])
  end
  
  def show
   # @book = Book.find(params[:id])
  end
  
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to books_path
  end
  
  def edit
    #@book = Book.find(params[:id])
  end
  
  def update
    #@book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to books_path
  end
  
  def destroy
    #@book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  ### ここからはprivate!!! ###
  private
  def book_params
    params.require(:book).permit(:name, :price, :publish, :publish_date)
  end
  
end

book_shelf_v2/app/helpers/application_helper.rb
module ApplicationHelper
end

book_shelf_v2/app/helpers/books_helper.rb
module BooksHelper
end

book_shelf_v2/app/views/books/edit.html.erb
<h2>書籍編集</h2>
<%= form_for @book do |f| %>
<div>
  書籍名: <%= f.text_field :name %>
</div>
<div>
  価格:   <%= f.number_field :price %>
</div>
<div>
  出版社: <%= f.text_field :publish %>
</div>
<div>
  刊行日: <%= f.date_field :publish_date %>
</div>
  
  <%= f.submit %>
<% end %>

book_shelf_v2/app/views/books/index.html.erb
<h1>書籍一覧</h1>
<% @books.each do |book| %>
  <li>
      <%= book.name %>
      <%= link_to "詳細", book_path(book) %>
      <%= link_to "編集", edit_book_path(book) %>
      <%= link_to "削除", book_path(book), method: :delete %>
  </li>
<% end %>

<%= link_to '新規登録', new_book_path %>

book_shelf_v2/app/views/books/new.html.erb
<h2>新規書籍登録</h2>
<%= form_for @book do |f| %>
<div>
  書籍名: <%= f.text_field :name %>
</div>
<div>
  価格:   <%= f.number_field :price %>
</div>
<div>
  出版社: <%= f.text_field :publish %>
</div>
<div>
  刊行日: <%= f.date_field :publish_date %>
</div>
  
  <%= f.submit %>
<% end %>

book_shelf_v2/app/views/books/show.html.erb
<h2>書籍詳細</h2>
<!--<%= @book.inspect %>-->-->
<p>ID: <%= @book.id %></p>
<p>書籍名: <%= @book.name %></p>
<p>価格: <%= @book.price %></p>
<p>出版社: <%= @book.publish %></p>
<p>刊行日: <%= @book.publish_date %></p>

book_shelf_v2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookShelfV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>